#+TITLE: My Emacs Literate Configuration
#+AUTHOR: Jonathan Prairie

* config.el
:PROPERTIES:
:header-args: :tangle config.el
:END:

I don't think this line is strictly necessary, isn't lexical binding the default now?

#+begin_src emacs-lisp
;;; $DOOMDIR/config.el -*- lexical-binding: t; -*-
#+end_src

#+begin_src emacs-lisp
(setq user-full-name "Jonathan Prairie"
      user-mail-address "jon.a.prairie@gmail.com")
(setq doom-font (font-spec :family "monospace" :size 12 :weight 'semi-light)
       doom-variable-pitch-font (font-spec :family "sans" :size 13))
#+end_src

deeper-blue is love

#+begin_src emacs-lisp
(setq doom-theme 'deeper-blue)
#+end_src

#+begin_src emacs-lisp
(setq org-directory "~/org/")
#+end_src

#+begin_src emacs-lisp
(setq display-line-numbers-type 'relative)
#+end_src

this function sends the space key (dec ascii code 32)

more documentation on unread-command-events: https://www.gnu.org/software/emacs/manual/html_node/elisp/Event-Input-Misc.html

Note: space character read form is '? ' (with a space! and no quotes)

#+begin_src emacs-lisp
(defun jp/send-space ()
  (interactive)
  (push '(t . 32) unread-command-events))
#+end_src

#+begin_src emacs-lisp
(map!
 "<f1>" help-map
 "<f3>" 'kill-this-buffer
 "<f5>" 'evil-prev-buffer
 "<f6>" 'evil-next-buffer
 "<f7>" 'evil-scroll-up
 "<f8>" 'evil-scroll-down
 "S-<f7>" 'evil-goto-first-line
 "S-<f8>" 'evil-goto-line

 "ESC h" 'evil-window-left
 "ESC l" 'evil-window-right
 "ESC j" 'evil-window-down
 "ESC k" 'evil-window-up

 "C-h" 'backward-kill-word
 )
#+end_src

#+begin_src emacs-lisp
(map!
 :n "U" 'evil-redo
 :n "H" 'evil-beginning-of-line
 :n "L" 'evil-end-of-line
 :n ";" 'evil-ex
 :n ":" 'evil-repeat-find-char
 )
#+end_src

#+begin_src emacs-lisp
(map! :leader
      :desc "M-x" ";" 'execute-extended-command
      :desc "Eval Expression" ":" 'pp-eval-expression)
#+end_src

add tangle to org-mode localleader keymap

#+begin_src emacs-lisp
(after! org-mode
  (map! :map org-mode-map
        :localleader
        :desc "tangle" "z" 'org-babel-tangle))
#+end_src

we want to set C-<SPC> to be an alternate leader key, but we want it to work in normal mode too.

Note: terminal emacs sees C-<SPC> as C-@ for some reason.

#+begin_src emacs-lisp
(setq doom-leader-alt-key "C-@")
(setq doom-localleader-alt-key "C-@ m")

(map! :n "C-@" 'jp/send-space)
#+end_src

tangle org files on save

from: https://systemcrafters.cc/emacs-from-scratch/configure-everything-with-org-babel/

#+begin_src emacs-lisp
(defun jp/org-babel-tangle ()
  (let ((file (buffer-file-name)))
  (async-start
   (lambda ()
     (require 'org)
     (let ((org-confirm-babel-evaluate nil))
       (org-babel-tangle-file file))))))

(add-hook
 'org-mode-hook
 (lambda () (add-hook 'after-save-hook #'jp/org-babel-tangle)))
#+end_src

don't pause before showing which-key buffer (still has an initial delay when emacs first starts up for some reason though)

more documentation here: https://github.com/justbur/emacs-which-key#other-options

#+begin_src emacs-lisp
(setq which-key-idle-delay 0.01)
#+end_src

disable rainbow delimiters everywhere

there's probably a better way to do this but it seems to work 🤷

#+begin_src emacs-lisp
(defun rainbow-delimiters-mode () nil)
#+end_src

setup some org-roam defaults

from: https://github.com/jethrokuan/dots/blob/master/.doom.d/config.el

Note: Need to configure c compile environment (MSYS2) if on Windows, before the form below will work

#+begin_src emacs-lisp
(use-package! org-roam
  :init
  (setq org-roam-directory (file-truename "~/org/zettel/")
        org-roam-db-gc-threshold most-positive-fixnum
        org-id-link-to-org-use-id t
        org-roam-completion-everywhere t
        org-roam-v2-ack t)
  ;; on Windows we need to set this to 'immediate, otherwise things run slowly for some reason
  ;; I think there's some sqlite timeout issues? See: https://github.com/org-roam/org-roam/issues/1289#issuecomment-744046148
  (setq org-roam-db-update-method 'immediate)
  :config
  (org-roam-db-autosync-mode +1)
  (setq org-roam-capture-templates
        '(("m" "main" plain
           "%?"
           :if-new (file+head "main/${slug}.org"
                              "#+title: ${title}\n")
           :immediate-finish t
           :unnarrowed t)
          ("r" "reference" plain "%?"
           :if-new
           (file+head "reference/${title}.org" "#+title: ${title}\n")
           :immediate-finish t
           :unnarrowed t)))
  (set-company-backend! 'org-mode '(company-capf))
  (cl-defmethod org-roam-node-type ((node org-roam-node))
    "Return the TYPE of NODE."
    (condition-case nil
        (file-name-nondirectory
         (directory-file-name
          (file-name-directory
           (file-relative-name (org-roam-node-file node) org-roam-directory))))
      (error "")))
  (setq org-roam-node-display-template
        (concat "${type:15} ${title:*} " (propertize "${tags:10}" 'face 'org-tag))))
(org-roam-setup)
#+end_src

Ignore weird lsp issues

#+begin_src emacs-lisp
(setq lsp-restart 'ignore)
#+end_src
